### ISSUE TITLE
README update needed?

### ISSUE THREAD

**Issue by ernewton** [awmann/M_-M_K-#5]
I get a very slight (and insignificant) difference in the resulting mass for GJ 1214 than in the README file when running the python snippet. TRAPPIST-1 (in python) is the same as the IDL code output.

print ("Mass=%6.4f+/-%6.4f" % (np.median(mass),np.std(mass)))
Mass=0.1803+/-0.0047

**Comment by awmann** [comment]
Ah, thanks for noting this. The reason is that I re-ran all the fits during the referee process and things changed very slightly (mostly the errors got a bit smaller), but I forgot to update that example. Now fixed.
